name:                polysemy-zoo
version:             0.1.1.0
github:              "isovector/polysemy-zoo"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "2019 Sandy Maguire"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Experimental, user-contributed effects and interpreters for polysemy
category:            Polysemy

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/isovector/polysemy-zoo#readme>

dependencies:
- base >= 4.7 && < 5
- polysemy
- polysemy-plugin
- mtl >= 2.0.1.0 && < 3.0.0.0
- containers
- reflection
- constraints
- random-fu
- random-source

ghc-options:
  - -fplugin=Polysemy.Plugin

  # Enable these when building haddock
  # - -fdefer-type-errors
  # - -fno-warn-deferred-type-errors

default-extensions:
  - DataKinds
  - DeriveFunctor
  - FlexibleContexts
  - GADTs
  - LambdaCase
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeOperators
  - TypeFamilies
  - UnicodeSyntax

library:
  source-dirs: src

tests:
  polysemy-zoo-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - polysemy-zoo
    - hspec
    - text