name:                polysemy-zoo
version:             0.5.0.1
github:              "isovector/polysemy-zoo"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "2019 Sandy Maguire"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Experimental, user-contributed effects and interpreters for polysemy
category:            Polysemy

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/isovector/polysemy-zoo#readme>

dependencies:
- base >= 4.9 && < 5
- constraints >= 0.10.1 && < 0.12
- containers >= 0.5 && < 0.7
- contravariant < 2
- mtl >= 2.0.1.0 && < 3.0.0.0
- stm >= 2 && < 3
- polysemy >= 1.1.0.0
- polysemy-plugin >= 0.2
- random >= 1.1 && <1.2
- reflection >= 2.1.4 && < 3.0.0
- transformers >= 0.5.2.0 && < 0.6
- ghc-prim >= 0.5.2 && < 0.6
- hedis >= 0.10 && < 0.13
- async >= 2.2 && < 3
- binary >= 0.8.5.1 && < 0.9
- bytestring >= 0.10.8.2 && < 0.11


ghc-options:
  - -fplugin=Polysemy.Plugin
  - -Wall

#   # Enable these when building haddock
#   - -fdefer-type-errors
#   - -fno-warn-deferred-type-errors

default-extensions:
  - DataKinds
  - DeriveFunctor
  - FlexibleContexts
  - GADTs
  - LambdaCase
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeOperators
  - TypeFamilies
  - UnicodeSyntax

library:
  source-dirs: src

tests:
  polysemy-zoo-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    build-tools:
    - hspec-discover  >= 2.0
    dependencies:
    - polysemy >= 1.1.0.0
    - polysemy-zoo
    - hspec >= 2.6.0 && < 3

